import { Property } from './types';

export const PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Azure Bay Mansion',
    location: 'Malibu, California',
    price: 12500000,
    beds: 6,
    baths: 8,
    sqft: 8500,
    type: 'Mansion',
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=1200',
    description: 'A stunning contemporary mansion overlooking the Pacific Ocean with floor-to-ceiling glass walls and a private infinity pool.',
    amenities: ['Infinity Pool', 'Home Theater', 'Wine Cellar', 'Private Beach Access'],
    coordinates: { lat: 34.0259, lng: -118.7798 }
  },
  {
    id: '2',
    title: 'The Obsidian Penthouse',
    location: 'Manhattan, New York',
    price: 8900000,
    beds: 3,
    baths: 4,
    sqft: 4200,
    type: 'Penthouse',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1200',
    description: 'Ultra-luxurious penthouse in the heart of Manhattan featuring panoramic city views and bespoke Italian finishes.',
    amenities: ['24/7 Concierge', 'Private Elevator', 'Roof Terrace', 'Smart Home System'],
    coordinates: { lat: 40.7589, lng: -73.9851 }
  },
  {
    id: '3',
    title: 'Emerald Valley Villa',
    location: 'Tuscany, Italy',
    price: 4200000,
    beds: 5,
    baths: 5,
    sqft: 5600,
    type: 'Villa',
    image: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=1200',
    description: 'Historic Tuscan villa restored to perfection, surrounded by olive groves and vineyards.',
    amenities: ['Vineyard', 'Guest House', 'Outdoor Kitchen', 'Spa'],
    coordinates: { lat: 43.7711, lng: 11.2486 }
  },
  {
    id: '4',
    title: 'Skyline Horizon Apartment',
    location: 'Dubai, UAE',
    price: 2800000,
    beds: 2,
    baths: 3,
    sqft: 2100,
    type: 'Apartment',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200',
    description: 'Modern apartment in the iconic Downtown Dubai district with direct views of the Burj Khalifa.',
    amenities: ['Gym', 'Pool', 'Parking', 'Security'],
    coordinates: { lat: 25.2048, lng: 55.2708 }
  },
  {
    id: '5',
    title: 'Alpine Retreat Chalet',
    location: 'Aspen, Colorado',
    price: 15700000,
    beds: 7,
    baths: 9,
    sqft: 10200,
    type: 'Mansion',
    image: 'https://images.unsplash.com/photo-1513584684374-8bdb7489feef?auto=format&fit=crop&q=80&w=1200',
    description: 'The ultimate ski-in/ski-out mountain estate with rustic charm and modern luxury.',
    amenities: ['Ski-in/Ski-out', 'Sauna', 'Heated Floors', 'Mountain Views'],
    coordinates: { lat: 39.1911, lng: -106.8175 }
  },
  {
    id: '6',
    title: 'Zen Garden Residence',
    location: 'Kyoto, Japan',
    price: 3500000,
    beds: 4,
    baths: 3,
    sqft: 3800,
    type: 'Villa',
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=1200',
    description: 'A serene residence blending traditional Japanese architecture with contemporary minimalist design.',
    amenities: ['Zen Garden', 'Tea Room', 'Natural Hot Spring', 'Library'],
    coordinates: { lat: 35.0116, lng: 135.7681 }
  },
  {
    id: '7',
    title: 'Pacific Horizon Estate',
    location: 'Malibu, California',
    price: 18900000,
    beds: 5,
    baths: 7,
    sqft: 7200,
    type: 'Mansion',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1200',
    description: 'An architectural marvel perched on the cliffs of Malibu with private beach access and 270-degree ocean views.',
    amenities: ['Private Beach', 'Infinity Pool', 'Home Gym', 'Smart Home'],
    coordinates: { lat: 34.0259, lng: -118.7798 }
  },
  {
    id: '8',
    title: 'Central Park Vista',
    location: 'Manhattan, New York',
    price: 12400000,
    beds: 4,
    baths: 4,
    sqft: 3800,
    type: 'Penthouse',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=1200',
    description: 'A rare penthouse offering direct views of Central Park with a massive private terrace and world-class amenities.',
    amenities: ['Terrace', 'Concierge', 'Fitness Center', 'Library'],
    coordinates: { lat: 40.7851, lng: -73.9683 }
  },
  {
    id: '9',
    title: 'Olive Grove Manor',
    location: 'Tuscany, Italy',
    price: 5600000,
    beds: 6,
    baths: 6,
    sqft: 6800,
    type: 'Villa',
    image: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&q=80&w=1200',
    description: 'A beautifully restored 18th-century manor set amidst rolling hills and ancient olive groves.',
    amenities: ['Pool', 'Wine Cellar', 'Guest House', 'Garden'],
    coordinates: { lat: 43.7711, lng: 11.2486 }
  },
  {
    id: '10',
    title: 'Palm Jumeirah Sanctuary',
    location: 'Dubai, UAE',
    price: 9200000,
    beds: 5,
    baths: 6,
    sqft: 8200,
    type: 'Villa',
    image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&q=80&w=1200',
    description: 'An exclusive beachfront villa on the Palm Jumeirah with private pool and private beach access.',
    amenities: ['Beach Access', 'Pool', 'Cinema Room', 'Staff Quarters'],
    coordinates: { lat: 25.1124, lng: 55.1390 }
  },
  {
    id: '11',
    title: 'Silver Peak Lodge',
    location: 'Aspen, Colorado',
    price: 21000000,
    beds: 8,
    baths: 10,
    sqft: 12500,
    type: 'Mansion',
    image: 'https://images.unsplash.com/photo-1544984243-ec57ea16fe25?auto=format&fit=crop&q=80&w=1200',
    description: 'A grand mountain lodge featuring massive timber beams, stone fireplaces, and unparalleled ski access.',
    amenities: ['Ski Access', 'Spa', 'Wine Room', 'Theater'],
    coordinates: { lat: 39.1911, lng: -106.8175 }
  },
  {
    id: '12',
    title: 'Sakura Blossom Villa',
    location: 'Kyoto, Japan',
    price: 4800000,
    beds: 5,
    baths: 4,
    sqft: 4500,
    type: 'Villa',
    image: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&q=80&w=1200',
    description: 'A contemporary masterpiece inspired by traditional Japanese aesthetics, featuring a private onsen and rock garden.',
    amenities: ['Onsen', 'Rock Garden', 'Tea House', 'Gallery'],
    coordinates: { lat: 35.0116, lng: 135.7681 }
  }
];
